server:
  port: 8082
  servlet:
    context-path: /security

spring:
  thymeleaf:
    ##指定模板所在的目录
    prefix: classpath:/templates/
    ##检查模板路径是否存在
    check-template-location: true
    ##是否缓存
    cache: false
    ##后缀
    suffix: .html
    encoding: UTF-8
    mode: HTML5